language: php

node_js: 6
php:
  - 5.6
  - 7.1

before_install:
  - composer self-update

install:
  - composer install
  - npm install

before_script:
  - composer self-update
  - composer update
  - npm update

script:
  - npm run production
  - ./vendor/bin/phpunit
